### ISSUE TITLE
Enable intersphinx for documentation (aka expose `objects.inv` aka support)

### ISSUE THREAD

**Issue by gabrielfalcao** [sdispater/pendulum#190]
Hello thanks for this great project.
I'm using pendulum extensively at work and would love to link to the pendulum documentation by using [intersphinx](http://www.sphinx-doc.org/en/stable/ext/intersphinx.html)

For that to work pendulum's documentation need to expose an `objects.inv` but I could not find it, here is a list of urls I tried:

- [`pendulum.eustace.io/docs/objects.inv`](pendulum.eustace.io/docs/objects.inv)
- [`pendulum.eustace.io/latest/objects.inv`](pendulum.eustace.io/latest/objects.inv)
- [`pendulum.eustace.io/objects.inv`](pendulum.eustace.io/objects.inv)

Here are some examples of sphinx-based documentations and their respective `objects.inv`:

- [`https://botocore.readthedocs.io/en/latest/objects.inv`](https://botocore.readthedocs.io/en/latest/objects.inv)
- [`http://click.pocoo.org/latest/objects.inv`](http://click.pocoo.org/latest/objects.inv)
- [`https://python-consul.readthedocs.io/en/latest/objects.inv`](https://python-consul.readthedocs.io/en/latest/objects.inv)
- [`http://flask.pocoo.org/docs/latest/objects.inv`](http://flask.pocoo.org/docs/latest/objects.inv)

Please expose that on pendulum so we can link to its documentation ?

**Comment by ashb** [comment]
Given that the docs aren't written in sphinx I am guessing this is non-trival

**Comment by cblegare** [comment]
@ashb It is indeed not trivial.

One could assemble and Inventory using [sphobjinv](https://sphobjinv.readthedocs.io/en/latest/) but this would be tedious.

But Sphinx is one of the best documentation processor in my opinion, and its `intersphinx` is simply amazing.

More and more libraries use Mkdocs, no sphinx, no inventory (FastAPI, Pydantic, to name a few).  Theses along with Pendulum developers take a great care to write good documentation and this is nice.  I get that some people might prefer Markdown over RestructuredText, but still, not leveraging Sphinx and not offering integration for Sphinx users saddens me a bit, even more because of the fact that Sphinx is optimised for prose (unlike Doxygen, for instance) and not for generated API doc.

I would like to read about the advantages of Mkdocs and why it is chosen over Sphinx.  Easier to style? Hate of RestructuredText (which is sometimes a bit akward I agree)?

If there could be a compromise possible, I'd try to submit PRs to Sphinx, user libraries, extensions or Mkdocs if anything could be done to help.

**Comment by Jorricks** [comment]
Let me break the silence here:
It appears we are now using `mkdocs` to build the library.
We could simply add a plugin called `mkdocstrings` which also supports this Sphinx inventory files.
A simple addition to `mkdocs.yml` would look like such:
```
# Plugins
plugins:
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          options:
            show_root_heading: true
            docstring_style: sphinx
            show_signature_annotations: false
            show_source: true
            docstring_options:
              ignore_init_summary: yes
``` 
What we'd have to check for is whether `mkdocstrings` would work with the pendulum theme.
I'll probably have a check somewhere in the upcoming months on whether I could fix this.
