### ISSUE TITLE
Pendulum doesn't support pep 517 builds

### ISSUE THREAD

**Issue by sbuniak-devkit** [sdispater/pendulum#781]
Reproduce issue with building image from Dockerfile:

```docker
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt upgrade
RUN apt install curl wget build-essential -y
# RUN apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.11 -y
# ENV PYTHON_VERSION=3.11
# install poetry
RUN curl -sSL https://install.python-poetry.org | python3.11 -
# Add Poetry to the PATH
ENV PATH="${PATH}:/root/.poetry/bin"
ENV PATH="/root/.local/bin:$PATH"
COPY pyproject.toml /pyproject.toml
RUN poetry env use 3.11 && poetry install
CMD ["bash"] 
```

pyproject.toml:

```toml
[tool.poetry]
name = "test_docker"
version = "0.1.0"
description = "Test python3.11 in docker"
authors = ["John Doe <john.doe@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11, <3.12"

# main packages
aiofiles = "^23.2.1"
aiohttp = "^3.9.0"
aioitertools = "^0.11.0"
apache-airflow = "2.7.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
force_single_line = true
line_length = 100
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
```

- **OS version and name**:  Ubuntu 20.04
- **Pendulum version**: 2.1.2

**NOTE**: apache-airflow needs pendulum ">=2.0, <3.0"

Although command 'pip wheel --no-cache-dir --use-pep517 "pendulum (==2.1.2)"' runs successfully, I'm not able to install pendulum with poetry and python 3.11 (it was working on python 3.8 earlier)
